export const WeatherCodes = {

    "0": {"name":"Despejado", "img":"despejado"},
    "1": {"name":"Mayormente despejado", "img":"despejado"}, 
    "2": {"name":"Parcialmente nublado", "img":"parcial_nublado"}, 
    "3": {"name":"Nublado", "img":"nublado"},
    "45": {"name":"Niebla", "img":"niebla"}, 
    "48": {"name":"Niebla con escarcha", "img":"niebla"},
    "51": {"name":"Llovizna ligera", "img":"llovizna_ligera"}, 
    "53": {"name":"Llovizna moderada", "img":"llovizna_moderada"}, 
    "55": {"name":"Llovizna densa", "img":"llovizna_densa"},
    "56": {"name":"Llovizna helada ligera", "img":"llovizna_ligera"}, 
    "57": {"name":"Llovizna helada densa", "img":"llovizna_densa"},
    "61": {"name":"Lluvia leve", "img":"lluvia_leve"}, 
    "63": {"name":"Lluvia moderada", "img":"lluvia_moderada"}, 
    "65": {"name":"Lluvia fuerte", "img":"lluvia_fuerte"},
    "66": {"name":"Lluvia helada ligera", "img":"lluvia_leve"}, 
    "67": {"name":"Lluvia helada fuerte", "img":"lluvia_fuerte"},
    "71": {"name":"Nieve ligera", "img":"nieve_ligera"}, 
    "73": {"name":"Nieve moderada", "img":"nieve_moderada"}, 
    "75": {"name":"Nieve densa", "img":"nieve_densa"},
    "77": {"name":"Granizo", "img":"granizo"},
    "80": {"name":"Chubascos leves", "img":"chubascos_leves"}, 
    "81": {"name":"Chubascos moderados", "img":"chubascos_moderados"}, 
    "82": {"name":"Chubascos violentos", "img":"chubascos_violentos"},
    "85": {"name":"Chubascos de nieve ligeros", "img":"chubascos_nieve_ligeros"}, 
    "86": {"name":"Chubascos de nieve fuertes", "img":"chubascos_nieve_fuertes"},
    "95": {"name":"Tormenta leve o moderada", "img":"tormenta"},
    "96": {"name":"Tormenta con granizo leve", "img":"tormenta_granizo_leve"}, 
    "99": {"name":"Tormenta con granizo fuerte", "img":"tormenta_granizo_fuerte"}
    
  };